using System.Diagnostics;
namespace RalExtractorByDateRange.Models
{
    [DebuggerDisplay("ID = {ID}, CreateDate = {CreateDate}")]
    public class Measures
    {
        public string Agent { get; set; }
        public string AgentGroup { get; set; }
        public string Agitation { get; set; }
        public string ANI { get; set; }
        public string AudioProfile { get; set; }
        public string BucketCount { get; set; }
        public string CallDate { get; set; }
        public string ClientCaptureDate { get; set; }
        public string ClientCaptureDateUT { get; set; }
        public string ClientID { get; set; }
        public string Comment { get; set; }
        public string ConfidenceAverage { get; set; }
        public string ConfidenceStandardDeviation { get; set; }
        public string ContentGroup { get; set; }
        public string CreateDate { get; set; }
        public string CTIEventList { get; set; }
        public string CustomerAccount { get; set; }
        public string Dept { get; set; }
        public string Description { get; set; }
        public string Direction { get; set; }
        public string Disposition_01 { get; set; }
        public string Disposition_02 { get; set; }
        public string Disposition_03 { get; set; }
        public string Disposition_04 { get; set; }
        public string Disposition_05 { get; set; }
        public string Disposition_06 { get; set; }
        public string DNIS { get; set; }
        public string EnteredQueueDate { get; set; }
        public string ExitStatus { get; set; }
        public string Extension { get; set; }
        public string ID { get; set; }
        public string Incident_01 { get; set; }
        public string Incident_02 { get; set; }
        public string IndexLength { get; set; }
        public string Location { get; set; }
        public string LocationCallID { get; set; }
        public string Noise_percent { get; set; }
        public string NoiseDurationAverageSeconds { get; set; }
        public string NoiseDurationMaxSeconds { get; set; }
        public string NoiseDurationMinSeconds { get; set; }
        public string NoiseDurationTotalSeconds { get; set; }
        public string NoiseLocationWeightedAverageSeconds { get; set; }
        public string NoiseTotalSegments { get; set; }
        public string ParentID { get; set; }
        public string PathMode { get; set; }
        public string ReferrerURL { get; set; }
        public string SequenceID { get; set; }
        public string SequencePosition { get; set; }
        public string Silence_LocationPercent { get; set; }
        public string Silence_percent { get; set; }
        public string SilenceDurationAverageSeconds { get; set; }
        public string SilenceDurationMaxSeconds { get; set; }
        public string SilenceDurationMinSeconds { get; set; }
        public string SilenceDurationTotalSeconds { get; set; }
        public string SilenceLocationWeightedAverageSeconds { get; set; }
        public string SilenceTotalSegments { get; set; }
        public string SiteName { get; set; }
        public string SourceDocumentType { get; set; }
        public string SourceDocumentTypeName { get; set; }
        public string SourceSQLServer { get; set; }
        public string StressAverage { get; set; }
        public string StressMax { get; set; }
        public string StressMin { get; set; }
        public string StressStandardDeviation { get; set; }
        public string Subject { get; set; }
        public string TempoAverageWordsPerMinute { get; set; }
        public string TotalHoldCount { get; set; }
        public string TotalHoldSeconds { get; set; }
        public string TotalSilenceSeconds { get; set; }
        public string TransferFrom { get; set; }
        public string TransferTo { get; set; }
        public string UDF_bigtext_01 { get; set; }
        public string UDF_bigtext_02 { get; set; }
        public string UDF_Date_01 { get; set; }
        public string UDF_Date_02 { get; set; }
        public string UDF_Int_01 { get; set; }
        public string UDF_Int_02 { get; set; }
        public string UDF_Int_03 { get; set; }
        public string UDF_Int_04 { get; set; }
        public string UDF_Int_05 { get; set; }
        public string UDF_Int_06 { get; set; }
        public string UDF_Int_07 { get; set; }
        public string UDF_Int_08 { get; set; }
        public string UDF_Int_09 { get; set; }
        public string UDF_Int_10 { get; set; }
        public string UDF_Int_11 { get; set; }
        public string UDF_Int_12 { get; set; }
        public string UDF_Int_13 { get; set; }
        public string UDF_Int_14 { get; set; }
        public string UDF_Int_15 { get; set; }
        public string UDF_num_01 { get; set; }
        public string UDF_num_02 { get; set; }
        public string UDF_num_03 { get; set; }
        public string UDF_num_04 { get; set; }
        public string UDF_num_05 { get; set; }
        public string UDF_num_06 { get; set; }
        public string UDF_num_07 { get; set; }
        public string UDF_num_08 { get; set; }
        public string UDF_num_09 { get; set; }
        public string UDF_Real_01 { get; set; }
        public string UDF_Real_02 { get; set; }
        public string UDF_Real_03 { get; set; }
        public string UDF_Real_04 { get; set; }
        public string UDF_Real_05 { get; set; }
        public string UDF_SmallDate_01 { get; set; }
        public string UDF_SmallDate_02 { get; set; }
        public string UDF_text_01 { get; set; }
        public string UDF_text_02 { get; set; }
        public string UDF_text_03 { get; set; }
        public string UDF_text_04 { get; set; }
        public string UDF_text_05 { get; set; }
        public string UDF_text_06 { get; set; }
        public string UDF_text_07 { get; set; }
        public string UDF_text_08 { get; set; }
        public string UDF_text_09 { get; set; }
        public string UDF_text_10 { get; set; }
        public string UDF_text_11 { get; set; }
        public string UDF_text_12 { get; set; }
        public string UDF_text_13 { get; set; }
        public string UDF_text_14 { get; set; }
        public string UDF_text_15 { get; set; }
        public string UDF_text_16 { get; set; }
        public string UDF_text_17 { get; set; }
        public string UDF_text_18 { get; set; }
        public string UDF_text_19 { get; set; }
        public string UDF_text_20 { get; set; }
        public string UDF_text_21 { get; set; }
        public string UDF_text_22 { get; set; }
        public string UDF_text_23 { get; set; }
        public string UDF_text_24 { get; set; }
        public string UDF_text_25 { get; set; }
        public string UDF_text_26 { get; set; }
        public string UDF_text_27 { get; set; }
        public string UDF_text_28 { get; set; }
        public string UDF_text_29 { get; set; }
        public string UDF_text_30 { get; set; }
        public string UDF_UID_01 { get; set; }
        public string UseDefaultCredentials { get; set; }
        public string WaitTimeSeconds { get; set; }
        public string WAVLength { get; set; }
        public string WAVPath { get; set; }
        public string WordCount { get; set; }
    }
}